### PR TITLE
super hacky fix that works™

### PR DESCRIPTION
**Pull request by BluCobalt**
basically, it just totally bypasses the method that throws the error and edits the fields directly.

### CODE REVIEW

**Comment by BoogieMonster1O1** [comment]
sned one screenshot and i merge :tiny_potato:
this is epic btw
thanks!

**Review by BoogieMonster1O1 — APPROVED** [review]

**Review by hYdos — APPROVED** [review]
y'know... if someone just found out what those methods are meant to inherit i would fix these in intermediary. be nice if someone found them all

**Comment by BoogieMonster1O1** [comment]
@hYdos why merge send screenshot or i revert :concern:

**Comment by BoogieMonster1O1** [comment]
> y'know... if someone just found out what those methods are meant to inherit i would fix these in intermediary. be nice if someone found them all

there's the bossbar one, of course
there's one in packetbytebuf iirc
yep thats all i know

**Comment by hYdos** [comment]
> 
> 
> @hYdos why merge send screenshot or i revert :concern:

what

**Comment by BoogieMonster1O1** [comment]
> > @hYdos why merge send screenshot or i revert :concern:
> 
> what

send.
a.
screenshot.
of.
wither.

use sei for a bettr experience

**Comment by BluCobalt** [comment]
> @hYdos why merge send screenshot or i revert :concern:

screenshot in discord https://ptb.discord.com/channels/679635419045822474/770951821095206930/780478145110605904

**Comment by BluCobalt** [comment]
https://ptb.discord.com/channels/679635419045822474/770951821095206930/780479249844666439 and the dragon

**Comment by BluCobalt** [comment]
https://ptb.discord.com/channels/679635419045822474/770951821095206930/780480755574898720 and then proof it works on hypixel

**Comment by BoogieMonster1O1** [comment]
epic

**Pull request merged**
